# Generated by Django 2.2.4 on 2019-10-23 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_article_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='unlike_users',
            field=models.ManyToManyField(blank=True, related_name='unlike_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
