# Generated by Django 2.2.4 on 2019-10-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_unlike_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='unlike_users',
        ),
    ]
